spring:
  data:
    redis:
      port: 6379
      password: Whltaoin08_
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 0
          max-wait: 100ms
      host: www.varin.cn
